### ISSUE TITLE
Crédit insuffisant

### ISSUE THREAD

**Issue by sebfie** [Cocolis-1/cocolis-woocommerce#17]
Quand l'api répond une 401 sur la création de l'annonce ou autre que 200, il faut remonter le message dans les logs de la commande : 

<img width="296" alt="CleanShot 2021-09-06 at 08 54 32@2x" src="https://user-images.githubusercontent.com/862129/132173369-a7830044-88df-4542-9e9e-c1efe97233f9.png">

Cela permet de voir qu'on a par exemple un manque de crédit.

**Comment by btnalexandre** [comment]
Prochaine release ça sera déployé
