### ISSUE TITLE
Ajouter un bouton 'Creer l'annonce chez cocolis'

### ISSUE THREAD

**Issue by sebfie** [Cocolis-1/cocolis-woocommerce#18]
Dans l'admin sur une commande, quand on a pas d'annonce cocolis liée, il faut rajouter un bouton quelque part : 

- Créer l'annonce chez cocolis

**Comment by AntoineCocolis** [comment]
Alors, le bouton permet bien de créer la ride chez nous. 
Par contre en testant je me suis rendu compte que certaines notes de commandes ne partent pas au bon moment.
Celles ci-dessous sont actuellement envoyées dès que la ride passe en in_progress. Il faudrait envoyer 
<img width="226" alt="Capture d’écran 2021-10-04 à 11 06 26" src="https://user-images.githubusercontent.com/59686802/135824969-36e00da0-28d0-47c3-a4ed-1df5c8dd6d7e.png">

**Comment by btnalexandre** [comment]
@AntoineCocolis malheureusement ce n'est pas moi qui gère les webhooks mais l'API qui me les envois :)

@sebfie une idée ?

**Comment by sebfie** [comment]
Je comprends pas le soucis, c'est l'ordre?

**Comment by AntoineCocolis** [comment]
non c'est le moment auquel c'est envoyé.
Actuellement les 3 sont envoyés quand la ride passe en in_progress.
Il faudrait envoyer le lien de l'annonce publique dès que la ride passe en published.
Et les liens vers les pages de suivi dès que l'annonce est en created

**Comment by sebfie** [comment]
Oki, j'ai vu avec alex sur slack : 

Il va changer la logique pour : 
- Le message du lien publique sur l'event `ride_published`
- Le lien des suivis sur le `offer_accepted `

**Comment by AntoineCocolis** [comment]
Alors la logique proposée n'est pas bonne pour les liens de suivis. Ils faut les envoyer dès que l'annonce est créée chez nous.

Sinon je viens de tester et tout s'envoi toujours à `l'offer_accepted`
<img width="482" alt="Capture d’écran 2021-10-05 à 14 13 59" src="https://user-images.githubusercontent.com/59686802/136020188-9c405e92-ef9a-490a-ae2b-d9794e3b0956.png">
