### ISSUE TITLE
Gérer l'annulation

### ISSUE THREAD

**Issue by sebfie** [Cocolis-1/cocolis-woocommerce#19]
Il faut un bouton Annuler votre annonce chez cocolis qui fait appel au travail de : 

https://github.com/Cocolis-1/cocolis-php/issues/26

**Comment by btnalexandre** [comment]
<img width="304" alt="CleanShot 2021-09-22 at 18 48 39@2x" src="https://user-images.githubusercontent.com/13454856/134389397-17e2ba15-9d16-4cd8-9f85-59deb6adb83a.png">

Lors d'un refund, cela déclenche l'annulation côté Cocolis
