### ISSUE TITLE
Ajouter des commentaires sur la commande

### ISSUE THREAD

**Issue by sebfie** [Cocolis-1/cocolis-woocommerce#20]
Quand on effectue un appel API, ajouter un commentaire dans : 

![CleanShot 2021-09-16 at 10 42 34](https://user-images.githubusercontent.com/862129/133580454-2f48b3ce-faf4-49e1-8f5f-8d58c6388ff3.png)

- Creation de ride
- Annulation
- Reception de webhook

ATTENTION, FAIRE UNE NOTE PRIVEE, LE CLIENT NE DOIT PAS ETRE NOTIFIE

**Comment by btnalexandre** [comment]
Problème corrigé, cela a déjà été fait auparavant

**Comment by AntoineCocolis** [comment]
- [ ] Voici les textes à revoir sur les commentaires suivants : 

- Une offre a été publiée sur cocolis.fr -> L'annonce de livraison vient d'être publiée sur cocolis.fr
- L’URL de l’annonce publique : %s https://sandbox.cocolis.fr/ride-public/2-suspensions-osier-ikea-meuble-vintage-en-metal-1950-0369d436-4d88-4430-8896-7e48f8e46f3b -> Lien vers l'annonce : https://sandbox.cocolis.fr/ride-public/2-suspensions-osier-ikea-meuble-vintage-en-metal-1950-0369d436-4d88-4430-8896-7e48f8e46f3b
- URL de livraison de suivi de l’acheteur : %s https://sandbox.cocolis.fr/tracking/buyer/EFCC234CF9C13F6A -> Lien vers le suivi acheteur : https://sandbox.cocolis.fr/tracking/buyer/EFCC234CF9C13F6A
- URL de livraison de suivi du vendeur : https://sandbox.cocolis.fr/tracking/seller/245C8B1B0388E798 -> Lien vers le suivi vendeur : https://sandbox.cocolis.fr/tracking/seller/245C8B1B0388E798
- Cocolis a annulé le trajet associé à cette commande suite à votre remboursement client. -> L'annonce de livraison a été supprimée suite au remboursement.

- [ ] Les liens vers la ride publique et les pages de suivi affichés dans les notes ne correspondent pas aux informations de la ride.

**Comment by AntoineCocolis** [comment]
Ce point là n'a pas été traité, les liens affichés ne sont toujours pas ceux de la ride en question
>  Les liens vers la ride publique et les pages de suivi affichés dans les notes ne correspondent pas aux informations de la ride.

Je remarque que l'on envoi toujours des notes aux clients (cf captures). Il ne faut pas envoyer ce genre d'informations au client car nous envoyons deja nous des triggers mails. Ces commentaires ne doivent servir qu'à la personne qui opère le WooCommerce.
<img width="867" alt="Capture d’écran 2021-09-28 à 17 54 30" src="https://user-images.githubusercontent.com/59686802/135122441-1eaa7b6d-0b85-4e91-8fc7-dc1ede0ee587.png">

<img width="849" alt="Capture d’écran 2021-09-28 à 17 54 26" src="https://user-images.githubusercontent.com/59686802/135122438-6a2903c8-49f8-4c11-9b82-ccf65ee633cc.png">

**Comment by btnalexandre** [comment]
Pas de problème ça sera corrigé dans la nuit 🙂
