### ISSUE TITLE
Affichage du mauvais montant d'assurance dans le checkout

### ISSUE THREAD

**Issue by AntoineCocolis** [Cocolis-1/cocolis-woocommerce#22]
Je sais pas si c'est lié au module ou si c'est sur le site de test woocommerce. Si c'est pas lié au module alors pas besoin de t'embeter.

A l'étape du checkout le montant max assuré n'est pas le bon (cf capture il est affiché 500 alors qu'il devrait être affiché 3000€)

<img width="1440" alt="Capture d’écran 2021-09-24 à 17 06 28" src="https://user-images.githubusercontent.com/59686802/134697913-04f7c764-994b-4acf-a34b-1db27f2f85d3.png">

**Comment by btnalexandre** [comment]
#21

**Comment by btnalexandre** [comment]
Oui :)
